# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a816e6136156dcb61296762106ad97d65aaca8f6c00fe675130b92b9006af8fcba557b6a64b83770d22361ebfffc70c8707204e7d2f508e7973b199a4f127b70

test:
  secret_key_base: 5a4157bddb9f3dd7777c3cbb382173289735be26526957e54bc7bb981704355a26b514c44a45ea68ec1b68e7ef8d6b63259672e6aa53c6813e086387058a3104

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
